### ISSUE TITLE
What does "snippets" mean?

### ISSUE THREAD

**Issue by chris-martin** [rainbyte/haskell-ide-chart#11]
I didn't fill in the "Snippets" column in #9 because I don't know what feature that refers to.

**Comment by chris-martin** [comment]
> https://github.com/rainbyte/haskell-ide-chart/pull/9#issuecomment-294949250

Ah, I see.

In IntelliJ these are called "templates".

**Comment by rainbyte** [comment]
I cite my self from the PR:

Snippets are predefined pieces of code, some included by the plug-in, and you could add more by yourself.
Example: if I write case, it would show the following as possible completion

```
case ___ of
  __ -> ___
```
It is mostly for pieces of code that you write very often.

**Comment by rainbyte** [comment]
Yes, I suppose it is the same... I did not list it as completion, because it is not something about intelligent completion, it is more about code predefined by plug-in or user, which could be used even via abreviations.

Ide's often have this feature natively, but does not alway provide Haskell snippets, which are provided via external plug-ins
